version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    container_name: api
    image: cashforce-api
    ports:
      - 3001:3001
    volumes:
      - .:/app/backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=cashforce
      - DB_PORT=3306
      - APP_ENV=development
      - PORT=3001
    networks:
      - cashforce
    restart: always
  db:
    image: mysql:8.0.28
    container_name: db
    ports: 
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    restart: always
    networks:
      - cashforce
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE
networks:
  cashforce:
    name: cashforce